package org.nextrg.skylens.renderables

import com.mojang.blaze3d.pipeline.BlendFunction
import com.mojang.blaze3d.pipeline.RenderPipeline
import com.mojang.blaze3d.vertex.VertexFormat.DrawMode
import net.minecraft.client.gl.RenderPipelines
import net.minecraft.client.gl.UniformType
import net.minecraft.client.render.VertexFormats
import org.nextrg.skylens.Skylens

object Pipelines {
    val CIRCLE_CHART: RenderPipeline = RenderPipelines.register(
        RenderPipeline.builder()
            .withLocation(Skylens.id("circle_chart"))
            .withVertexShader(Skylens.id("core/basic_transform"))
            .withFragmentShader(Skylens.id("core/circle_chart"))
            .withBlend(BlendFunction.TRANSLUCENT)
            .withVertexFormat(VertexFormats.POSITION, DrawMode.QUADS)
            .withUniform("modelViewMat", UniformType.MATRIX4X4)
            .withUniform("projMat", UniformType.MATRIX4X4)
            .withUniform("color0", UniformType.VEC4)
            .withUniform("color1", UniformType.VEC4)
            .withUniform("color2", UniformType.VEC4)
            .withUniform("color3", UniformType.VEC4)
            .withUniform("color4", UniformType.VEC4)
            .withUniform("color5", UniformType.VEC4)
            .withUniform("color6", UniformType.VEC4)
            .withUniform("color7", UniformType.VEC4)
            .withUniform("colorCount", UniformType.INT)
            .withUniform("center", UniformType.VEC2)
            .withUniform("outerRadius", UniformType.FLOAT)
            .withUniform("innerRadius", UniformType.FLOAT)
            .withUniform("progress", UniformType.FLOAT)
            .withUniform("time", UniformType.FLOAT)
            .withUniform("startAngle", UniformType.FLOAT)
            .withUniform("reverse", UniformType.INT)
            .withUniform("invert", UniformType.INT)
            .build()
    )

    val ROUND_GRADIENT: RenderPipeline = RenderPipelines.register(
        RenderPipeline.builder()
            .withLocation(Skylens.id("round_gradient"))
            .withVertexShader(Skylens.id("core/basic_transform"))
            .withFragmentShader(Skylens.id("core/round_gradient"))
            .withBlend(BlendFunction.TRANSLUCENT)
            .withVertexFormat(VertexFormats.POSITION, DrawMode.QUADS)
            .withUniform("modelViewMat", UniformType.MATRIX4X4)
            .withUniform("projMat", UniformType.MATRIX4X4)
            .withUniform("color0", UniformType.VEC4)
            .withUniform("color1", UniformType.VEC4)
            .withUniform("color2", UniformType.VEC4)
            .withUniform("color3", UniformType.VEC4)
            .withUniform("color4", UniformType.VEC4)
            .withUniform("color5", UniformType.VEC4)
            .withUniform("color6", UniformType.VEC4)
            .withUniform("color7", UniformType.VEC4)
            .withUniform("colorCount", UniformType.INT)
            .withUniform("size", UniformType.VEC2)
            .withUniform("center", UniformType.VEC2)
            .withUniform("borderColor", UniformType.VEC4)
            .withUniform("borderRadius", UniformType.VEC4)
            .withUniform("borderWidth", UniformType.FLOAT)
            .withUniform("scaleFactor", UniformType.FLOAT)
            .withUniform("time", UniformType.FLOAT)
            .withUniform("gradientDirection", UniformType.INT)
            .build()
    )

    val RADIAL_LINE: RenderPipeline = RenderPipelines.register(
        RenderPipeline.builder()
            .withLocation(Skylens.id("radial_line"))
            .withVertexShader(Skylens.id("core/basic_transform"))
            .withFragmentShader(Skylens.id("core/radial_line"))
            .withBlend(BlendFunction.TRANSLUCENT)
            .withVertexFormat(VertexFormats.POSITION, DrawMode.QUADS)
            .withUniform("modelViewMat", UniformType.MATRIX4X4)
            .withUniform("projMat", UniformType.MATRIX4X4)
            .withUniform("lineColor", UniformType.VEC4)
            .withUniform("center", UniformType.VEC2)
            .withUniform("radius", UniformType.FLOAT)
            .withUniform("startAngle", UniformType.FLOAT)
            .withUniform("angleThickness", UniformType.FLOAT)
            .withUniform("fadeSoftness", UniformType.FLOAT)
            .withUniform("thickness", UniformType.FLOAT)
            .withUniform("mode", UniformType.INT)
            .build()
    )

    val FLUID_CONTAINER: RenderPipeline = RenderPipelines.register(
        RenderPipeline.builder()
            .withLocation(Skylens.id("fluid_container"))
            .withVertexShader(Skylens.id("core/basic_transform"))
            .withFragmentShader(Skylens.id("core/fluid_container"))
            .withBlend(BlendFunction.TRANSLUCENT)
            .withVertexFormat(VertexFormats.POSITION, DrawMode.QUADS)
            .withUniform("modelViewMat", UniformType.MATRIX4X4)
            .withUniform("projMat", UniformType.MATRIX4X4)
            .withUniform("fillColor", UniformType.VEC4)
            .withUniform("size", UniformType.VEC2)
            .withUniform("center", UniformType.VEC2)
            .withUniform("borderColor", UniformType.VEC4)
            .withUniform("borderRadius", UniformType.VEC4)
            .withUniform("borderWidth", UniformType.FLOAT)
            .withUniform("scaleFactor", UniformType.FLOAT)
            .withUniform("time", UniformType.FLOAT)
            .withUniform("offsetX", UniformType.FLOAT)
            .withUniform("offsetY", UniformType.FLOAT)
            .withUniform("waveDirection", UniformType.INT)
            .build()
    )
}